# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22cb5ab2b57a9f80b8a7ec1bae8399d655a94660d61d09d7d68bc6fb935fa0870324c3498050141550b41aa1b1a70e19d1cb621eeaaab2cc1a22dea14b356437

test:
  secret_key_base: 4bbc4396fd0e5b7c98ee56dd854c2e33035a24dc487f16222ebeaa29936fc225417fa6a684b94c8c8e228f4a4598b04bfb30d17fbf4bf5631b773d6b14fa2b29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
