class ApplicationController < ActionController::Base
  # extends ....................................................................
  # includes ...................................................................
  # constants ..................................................................
  # filters ....................................................................
  # helpers ....................................................................
  # scopes .....................................................................
  # additional config ..........................................................

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  # controller actions .........................................................
end
