class User < ActiveRecord::Base
  # extends ....................................................................
  # includes ...................................................................
  # constants ..................................................................
  # associations ...............................................................
  # scopes .....................................................................
  # validations ................................................................
  # callbacks ..................................................................
  # additional config ..........................................................

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # class methods ..............................................................
  # instance methods ...........................................................
  # protected instance methods .................................................
  # private instance methods ...................................................
end
