<% module_namespacing do -%>
class <%= class_name %> < <%= parent_class_name.classify %>
  # extends ....................................................................
  # includes ...................................................................
  # constants ..................................................................
  # associations ...............................................................

<% attributes.select(&:reference?).each do |attribute| -%>
  belongs_to :<%= attribute.name %><%= ', polymorphic: true' if attribute.polymorphic? %>
<% end -%>

  # scopes .....................................................................
  # validations ................................................................
  # callbacks ..................................................................
  # additional config ..........................................................

<% if attributes.any?(&:password_digest?) -%>
  has_secure_password
<% end -%>

  # class methods ..............................................................
  # instance methods ...........................................................
  # protected instance methods .................................................
  # private instance methods ...................................................
end
<% end -%>
